pipeline {
    agent any
    stages {
        stage('Clone Repo') {
            steps {
                git 'https://github.com/your-username/django-todo-app.git'
            }
        }
        stage('Set Up Python') {
            steps {
                sh 'python3 -m venv venv'
                sh './venv/bin/pip install -r requirements.txt'
            }
        }
        stage('Run Tests') {
            steps {
                sh './venv/bin/python manage.py test'
            }
        }
        stage('Collect Static & Migrate') {
            steps {
                sh './venv/bin/python manage.py collectstatic --noinput'
                sh './venv/bin/python manage.py migrate'
            }
        }
        stage('Run Server') {
            steps {
                sh './venv/bin/python manage.py runserver'
            }
        }
    }
}
